#!/bin/sh

cap="/sys/class/power_supply/BAT0/capacity"
critical=10
interval=120

if [ ! -e $cap ]
then
	echo "No battery detected" >&2
	exit 1
fi

case $1 in
	-d|--daemon)
		while true
		do
			batc=$(sed 's/%//' $cap)
			[[ $batc -le $critical ]] && echo "BAT: $batc%" > $POPUP_FIFO

			sleep $interval
		done &
		echo "Daemon started"
		;;
	*)
		perc=$(acpi | grep -o "[0-9]\{1,3\}%")
		time=$(acpi | grep -o "[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}")
		echo "BAT: $perc ($time)" > $POPUP_FIFO
		;;
esac
