#!/bin/sh

# Check if xdo is installed
xdo_path=$(which xdo)
if [ $? -ne 0 ]; then
	echo "Cannot find \'xdo\' command." 1>&2
	exit 1
fi

if [ ! -f "/tmp/barvisible" ]; then
	barvisible=1
else
	barvisible=$(cat /tmp/barvisible)
fi

if [ "$barvisible" == 1 ]; then
	xdo hide -N "Bar"
	bspc config top_padding 0
	barvisible=0
else
	xdo show -N "Bar"
	barvisible=1
fi
echo $barvisible > /tmp/barvisible
